### PR TITLE
Fix missing closing braces

### LINKED ISSUE #1112: Config Show doesn't print close brace with MonitorApiKey present
In PowerShell, issue the following commands (from a directory with `dotnet-monitor.exe`
```powershell
$env:Authentication__MonitorApiKey__Subject="ae5473b6-8dad-498d-b915-ffffffffffff"
$env:Authentication__MonitorApiKey__PublicKey="eyffffffffffffFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiTnhIRnhVZ19QM1dhVUZWVzk0U3dUY3FzVk5zNlFLYjZxc3AzNzVTRmJfQ3QyZHdpN0RWRl8tUTVheERtYlJuWSIsIlg1YyI6W10sIlkiOiJmMXBDdmNoUkVpTWEtc1h6SlZQaS02YmViMHdrZmxfdUZBN0Vka2dwcjF5N251Wmk2cy1NcHl5RzhKdVFSNWZOIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmplY3RQb29sQ2FjaGffffffffffff19"
.\dotnet-monitor.exe config show
```

The expected output would have a valid-formatted json blob. This is what is actually printed:
```json
{
  "urls": "https://localhost:52323",
  "Kestrel": ":NOT PRESENT:",
  "GlobalCounter": {
    "IntervalSeconds": "5"
  },
  "CollectionRules": ":NOT PRESENT:",
  "CorsConfiguration": ":NOT PRESENT:",
  "DiagnosticPort": {
    "ConnectionMode": "Connect",
    "EndpointName": null
  },
  "Metrics": {
    "Enabled": "True",
    "Endpoints": "http://localhost:52325",
    "IncludeDefaultProviders": "True",
    "MetricCount": "3"
  },
  "Storage": {
    "DumpTempFolder": "C:\\Users\\pafenelo\\AppData\\Local\\Temp\\"
  },
  "DefaultProcess": ":NOT PRESENT:",
  "Logging": {
    "Console": {
      "FormatterName": "simple",
      "FormatterOptions": {
        "IncludeScopes": "True",
        "TimestampFormat": "HH:mm:ss "
      }
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Diagnostics": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Diagnostics": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Authentication": {
    "MonitorApiKey": {
      "Subject": "2c866b1a-38c5-4454-a686-1e022e38a7f6",
      "PublicKey": ":REDACTED:",
      "Egress": ":NOT PRESENT:"
    }
```

### PR DESCRIPTION
**Pull request by kelltrick**
- Fixes missing closing braces when executing `dotnet monitor show config` with `Authentication` section present.
- Replaces `_writer.WriteStartObject();` and `_writer.WriteEndObject();` calls with new `JsonSectionHolder` that can be used in a C# `using (...)` scope.

Old output from `dotnet monitor show config` (with `Authentication__MonitorApiKey__Subject` and `Authentication__MonitorApiKey__PublicKey` set via environment variables)
``` json
{
  // omitted for clarity
  "Authentication": {
    "MonitorApiKey": {
      "Subject": "2c866b1a-38c5-4454-a686-1e022e38a7f6",
      "PublicKey": ":REDACTED:",
      "Egress": ":NOT PRESENT:"
    }
```
New output:
``` json
{
  // omitted for clarity
  "Authentication": {
    "MonitorApiKey": {
      "Subject": "2c866b1a-38c5-4454-a686-1e022e38a7f6",
      "PublicKey": ":REDACTED:"
    }
  },
  "Egress": ":NOT PRESENT:"
}
```

Closes #1112

### CODE REVIEW

File: src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs [hunk 1]
```diff
@@ -217,5 +230,22 @@ public void Dispose()
         {
             _writer.Dispose();
         }
+
+        private class JsonSectionHolder : IDisposable
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs:234]: nit: Since it does more than just holding it and holders typically have the ownership to dispose what they are holding, how about naming it something like `JsonObjectContext` or `JsonObjectSection`.

Comment (kelltrick) [reply src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs:234]: Ahh, I like `[Json]ObjectContext`. I was trying to come up with a name that involved `object` but couldn't come up with something I liked better than `[Json]SectionHolder`

**Review by wiktork — APPROVED** [review]
