### PR TITLE
Handles incorrectly formatted settings.json files by catching the System.FormatException and outputting a readable error message for the user.

### LINKED ISSUE #203: Display friendly error message for malformed configuration
We should catch this exception and log a friendlier error message

```
Unhandled exception: System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 2 | BytePositionInLine: 2.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Diagnostics.Tools.Monitor.DiagnosticsMonitorCommandHandler.Start(CancellationToken token, IConsole console, String[] urls, String[] metricUrls, Boolean metrics, String diagnosticPort, Boolean noAuth) in /_/src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:line 68
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### PR DESCRIPTION
**Pull request by kkeirstead**
When the settings.json file is incorrectly configured, a crash results. This handles the error and gracefully exits with an error message pointing the user to the issue.

```
Could not parse the JSON file.
'"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 6 | BytePositionInLine: 33.
```

closes #203

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-monitor?pullRequest=446) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-monitor?pullRequest=446) before we can accept your contribution.<br/><br/>:x: kkeirstead [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-monitor?pullRequest=446)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-monitor?pullRequest=446) it.</sub>

File: src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs [hunk 1]
```diff
@@ -69,36 +69,44 @@ internal sealed class DiagnosticsMonitorCommandHandler
...
+                    if (host is IAsyncDisposable asyncDisposable)
+                    {
+                        await asyncDisposable.DisposeAsync();
+                    }
+                    else
+                    {
+                        host.Dispose();
+                    }
+                }
+            } catch (FormatException ex)
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:104]: nit: Move the catch to its own line. I know that is a formatting preference, but we try to keep the formatting consistent throughout, at least within a file.

File: src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs [hunk 2]
```diff
@@ -69,36 +69,44 @@ internal sealed class DiagnosticsMonitorCommandHandler
...
+            {
+                TextWriter errorWriter = Console.Error;
+                errorWriter.WriteLine(ex.Message + "\n" + ex.InnerException.Message);
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:107]: Break this up into two WriteLine calls, one for the message and one for the inner exception message, which lets the framework decide which set of characters to use for newlines.

File: src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs [hunk 3]
```diff
@@ -69,36 +69,44 @@ internal sealed class DiagnosticsMonitorCommandHandler
...
+                        await asyncDisposable.DisposeAsync();
+                    }
+                    else
+                    {
+                        host.Dispose();
+                    }
+                }
+            } catch (FormatException ex)
+            {
+                TextWriter errorWriter = Console.Error;
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:106]: nit: You can use Console.Error directly without putting it into a local. We're not too terrible concerned with performance here and accessing the property repeatedly has a negligible perf impact.

**Review by jander-msft — CHANGES_REQUESTED** [review]

File: src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs [hunk 4]
```diff
@@ -69,36 +69,44 @@ internal sealed class DiagnosticsMonitorCommandHandler
...
+                errorWriter.WriteLine(ex.Message + "\n" + ex.InnerException.Message);
             }
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:108]: You'll want to return a non-zero exit code in this case as well. Some systems check if the exit code is non-zero to determine a problem occurred rather than checking stderr since it is a quick indication that something went wrong.

File: src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs [hunk 5]
```diff
@@ -69,36 +69,47 @@ internal sealed class DiagnosticsMonitorCommandHandler
...
+                    else
+                    {
+                        host.Dispose();
+                    }
                 }
             }
+            catch (FormatException ex)
+            {
+                Console.Error.WriteLine(ex.Message);
+                Console.Error.WriteLine(ex.InnerException.Message);
```
Comment (jander-msft) [inline src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs:108]: One more change (that I should have stated before): null check ex.InnerException before attempting to access it.

**Review by jander-msft — APPROVED** [review]
