### PR TITLE
Write ndjson logs in same format at JsonConsoleFormatter and event-stream logs in format as SimpleConsoleFormatter

### LINKED ISSUE #190: Exception and EventId information are discarded from /logs route
If an application logs an entry with an exception, for example:

```cs
try
{
    throw new InvalidOperationException("Uh oh!");
}
catch (Exception ex)
{
    _logger.LogError(new EventId(7, "FailedAfterRetries"), ex, "Failed to get resource after {attempts} attempts.", 5);
}
```

The exception information is discarded in the output of the logs call, regardless of which output format is used:

application/x-ndjson:
```json
{
    "LogLevel": "Error",
    "EventId": "FailedAfterRetries",
    "Category": "MyNamespace.MyClass",
    "Exception": "Failed to get resource after 5 attempts.",
    "Scopes": {
        "RequestId": "8000000d-0004-fd00-b63f-84710c7967bb",
        "RequestPath": "/",
        "ActionId": "36874571-0555-49c3-8410-5107eb3b83e3",
        "ActionName": "/Index"
    },
    "Arguments": {
        "attempts": "5",
        "{OriginalFormat}": "Failed to get resource after {attempts} attempts."
    }
}
```

text/event-stream:
```
event: FailedAfterRetries
data: Error MyNamespace.MyClass[7]
data: Failed to get resource after 5 attempts.
data: => RequestId:80000010-0004-fd00-b63f-84710c7967bb, RequestPath:/ => ActionId:36874571-0555-49c3-8410-5107eb3b83e3, ActionName:/Index
```

Additionally, application/x-njdson doesn't have the ID of the EventId and text/event-stream doesn't have the event name of the EventId.

### PR DESCRIPTION
**Pull request by jander-msft**
C# code that logs:

```cs
try
{
    throw new InvalidOperationException("Uh oh!");
}
catch (Exception ex)
{
    _logger.LogError(new EventId(7, "FailedAfterRetries"), ex, "Failed to get resource after {attempts} attempts.", 5);
}
```

will appear in the `/logs` call (`application/x-ndjson`) as:

```json
{
    "LogLevel": "Error",
    "EventId": 7,
    "EventName": "FailedAfterRetries",
    "Category": "WebApplication1Pages.IndexModel",
    "Message": "Failed to get resource after 5 attempts.",
    "Exception": "System.InvalidOperationException: Uh oh!\r\n   at WebApplication1.Pages.IndexModel.OnGet() in C:\\Users\\username\\source\\WebApplication1\\WebApplication1\\Pages\\Index.cshtml.cs:line 25",
    "State": {
        "Message": "Failed to get resource after 5 attempts.",
        "attempts": "5",
        "{OriginalFormat}": "Failed to get resource after {attempts} attempts."
    },
    "Scopes": [
        {
            "RequestId": "80000005-0006-fd00-b63f-84710c7967bb",
            "RequestPath": "/",
            "SpanId": "|7cc52286-450013e8212a49b2.",
            "TraceId": "7cc52286-450013e8212a49b2",
            "ParentId": ""
        },
        {
            "ActionId": "fffe72c8-3237-4ef5-aff5-5760c829d34b",
            "ActionName": "/Index"
        }
    ]
}
```

(newlines and indents added for readability).

or (`text/event-stream`) as:

```
event: FailedAfterRetries
data: Error WebApplication1.Pages.IndexModel[7]
data: Failed to get resource after 5 attempts.
data: => RequestId:0HM892TCMKAOI:00000005, RequestPath:/, SpanId:|1dd6f6c7-4f0343320e3f6568., TraceId:1dd6f6c7-4f0343320e3f6568, ParentId: => ActionId:b54a79e8-1cf5-4e00-bc53-f21e50d2b87c, ActionName:/Index
data: System.InvalidOperationException: Uh oh!
data:    at WebApplication1.Pages.IndexModel.OnGet() in C:\Users\username\source\WebApplication1\WebApplication1\Pages\Index.cshtml.cs:line 26
```

Closes #190, #198

### CODE REVIEW

File: src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs [hunk 1]
```diff
@@ -84,40 +84,47 @@ private void LogJson<TState>(LogLevel logLevel, EventId eventId, TState state, E
...
                 jsonWriter.WriteString("Category", _categoryName);
+                jsonWriter.WriteString("Message", formatter(state, exception));
                 if (exception != null)
                 {
-                    jsonWriter.WriteString("Exception", formatter(state, exception));
-                }
-                else
-                {
-                    jsonWriter.WriteString("Message", formatter(state, exception));
+                    jsonWriter.WriteString("Exception", exception.ToString());
```
Comment (wiktork) [inline src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:98]: Did you want to change the text format to produce exception verbose information as well? Currently it always uses the formatter.

File: src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs [hunk 2]
```diff
@@ -84,40 +84,47 @@ private void LogJson<TState>(LogLevel logLevel, EventId eventId, TState state, E
             //CONSIDER Should we cache up the loggers and writers?
             using (var jsonWriter = new Utf8JsonWriter(outputStream, new JsonWriterOptions { Indented = false }))
             {
+                // Matches the format of JSONConsoleFormatter
+
                 jsonWriter.WriteStartObject();
+                // TODO: Write timestamp as string
+                //jsonWriter.WriteString("Timestamp", DateTime.UtcNow.ToString());
                 jsonWriter.WriteString("LogLevel", logLevel.ToString());
-                jsonWriter.WriteString("EventId", eventId.ToString());
```
Comment (wiktork) [inline src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:89]: EventId.ToString uses return Name ?? Id.ToString();
With this change, we are losing eventId.Name.

Comment (jander-msft) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:89]: JsonConsoleFormatter only returns the ID. Maybe we can add another property (`EventName`) for `EventId.Name` so that it remains at least a superset of JsonConsoleFormatter.

File: src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs (hunk 1 above)
Comment (jander-msft) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:98]: JsonConsoleFormatter uses `formatter(state, exception` for the `Message` property only and just calls `ToString` on the exception for the `Exception` property.

Comment (wiktork) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:98]: To clarify, I meant add another data: <exception.ToString()> to the text/event-stream format.

Comment (jander-msft) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:98]: Sure, I can do that. This change is only about the JSON format. I'll update event-stream next.

File: src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs (hunk 2 above)
Comment (jander-msft) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:89]: Added EventName; it is an empty string if `EventId.Name` is not specified.

File: src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs (hunk 1 above)
Comment (jander-msft) [reply src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs:101]: I added the event-stream update since it was simple.

**Review by wiktork — APPROVED** [review]
